var headerHTML = '<style>'
+'.demotitle{position: absolute;top: 5px;left: 10px;font-size: 24px;font-weight: bold;color: #777;}'
+'#headerInfo{position: absolute;	top: 0px;left: 0px;	height: 75px;z-index: 99999;background-color: rgba(0,0,0,.8);width: 100%;}'
+'a, a:link{color: #222;text-decoration:none;}a:visited { color: #999; }a:hover { color: #000; }a:focus { outline: thin dotted; }'
+'a:hover, a:active { outline: 0; }'
+'.links{float: right; opacity: 0.5; color:#222;}'
+'.navMenu{	color:#C9C9C9;	font-size: 12px;	position: absolute;	bottom: 3px;	right: 15px;}'
+'.links:hover{	opacity: 1;}'
+'</style>'
+'<div class="links" style="margin:0px; padding:0px;">'
+'<a href= "http://twitter.com/nichom" target="_blank">'
+'<img src="img/Twitter_logo_blue.png" height="30px" style="margin:7px"></a>'
+'</div>'
+'<div class="links" style="margin:0px; padding:0px;">'
+'<a href= "http://twitter.com/nichom" target="_blank">'
+'<img src="img/GitHub-Mark-64px.png" height="30px" style="margin:7px"></a>'
+'</div>';